# Infinite Bot 3 - ViewManager(游戏界面查看附属) 1.0
# 自带关键字列表 []表示监听范围 ()表示权限等级
#   - 我的背包 [全局] (无)
#   - 我的末影箱 [全局] (无)

# 消息互通功能增强
# 开启后，当游戏内发送 InteractiveChat 内配置的展示变量后，自动同步发送至QQ
# 提示：默认展示变量
# - [i] 或 [item], 展示手持物品
# - [inv] 或 [inventory], 展示背包物品
# - [e] 或 [ender], 展示末影箱物品
# 注意：此功能仅在ib3加装 消息互通 附属后且 game-to-group.enable 节点设置为 true 时可用
expand-chat: true