# Infinite Bot 3.1.0 - MessageManager(自定义消息附属)
#
# 所有自定义消息触发时都会自动回复触发者
#
# 内置变量(正在添加中)
# > 特殊（特殊内置变量以{#name}的形式调用，部分仅可在指定 show-type 中使用）
# - {#sender}: @消息触发者
# - {#reply}: 将该条消息设置为回复消息
# > 通用（通用内置变量以{name}的形式调用，允许在所有 show-type 中使用）
# - {senderName}: 消息触发者名称，若无法获取则返回发送者qq

# 消息文件储存的相对路径
#   若不存在则会自动创建
folder: '/message'

# 自定义静态变量，在 content 节点中使用 {名称} 调用
# 优先级：papi变量 > 自定义静态变量
# !! 暂不支持嵌套使用
custom-placeholder:
  自定义变量: 'Hello World'
