# Infinite Bot 3.0.3 - BasicManager(基础管理)
#
# 自带关键字列表 []表示监听范围 ()表示权限等级
#   - 今日新玩家 [全局] (管理员)
#   - 我的绑定 [全局] (无)
#   - 强制下线 [全局] (无)
#   - 服务器在线 [组] (无)
#
# 基础申请绑定: [组] (无)
#   玩家在群内发送 '绑定 正版/离线 玩家名称'
# 在游戏内按指示输入即可完成绑定
#
# 更改绑定: [组] (无)
#   玩家在群内发送 '改绑 正版/离线 玩家名称'
# 在游戏内按指示输入即可完成改定

# QQ提交服务器指令 [全局] (管理员)
submit:
  # 前缀 (例: 'cmd help')
  prefix: cmd
  # 合并消息等待时长，若设置为 0 则不进行等待
  delay-tick: 5
  # 命令执行器的显示名称
  sender-name: 'console'

# 基础绑定设置
bind:
  # 验证码有效时长 (单位: 分钟)
  limit: 5

# 成员监听
member-manage:
  # 是否自动同意群成员加入
  auto-accept: true
  # 自动将发言过的玩家的群名片改成其游戏名
  # 优先选取离线UUID名称
  auto-change-card: true
  # 默认群名片
  # 当成员未绑定角色时，设置为该名片
  default-card: '待绑定'
  # 是否修改群管理员的名片
  change-admin: false
  # 群成员加入时欢迎语 (自动@该成员)
  # 局部变量 {0}-成员QQ
  welcome:
    - '欢迎{0}加入xxx'
