# Infinite Bot 3.1.7 - LandlordsGame(斗地主)
#
# 使用本附属时，请将您的 basic-manager 附属升级至2023-01-06之后的版本

# 关键词配置
keyword:
  help: '斗地主帮助'
  # 加入游戏
  join: '加入斗地主'
  # 抢地主 关键词
  grab: '抢地主'
  # 不抢地主 关键词
  disgrab: '不抢'
  # 出牌关键词前缀，玩家使用该前缀+牌名称(牌与牌直接需加空格)进行出牌
  # 例：
  #   send: '出牌'
  #   出牌 3 4 5 6 7
  # 牌的种类名称为
  # 3 4 5 6 7 8 9 10 J Q K A 2 小王 大王
  send: '出牌'
  # 不出牌
  dissend: '不要'
  # 中止对局指令 仅管理员可用
  stop: '中止游戏'
  # 查看自身手牌，仅私聊可用
  see: '查看手牌'

