# Infinite Bot 3.1.0 - GithubManager(Github小助手附属)
#

# 通知设置
notice:
  # 需要通知的好友
  user:
    - 765743073
  # 需要通知的群组
  group:
    - 863522624

# 仓库功能配置
repo:
  # 更新监听配置
  # 监听指定仓库的 commit 与 release
  # 注：若本次获取的更新版本与上次获取并记录的版本间
  #   存在多个更新，则会将其全部列出
  listener:
    # 是否开启 commit 更新监听
    enable-commit: true
    # 是否开启 release 更新监听
    enable-release: true
    # 自动查询周期（单位：分钟）
    period: 1
    # 监听仓库 URI
    uri:
      - 'IllTamer/infinitebot3'


